name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.7
      - run: pinact run --check
